# Generated by Django 4.1.7 on 2023-04-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='POA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='aadh',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='ph',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
