# Generated by Django 4.1.7 on 2023-04-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_seller_poa_alter_seller_aadh_alter_seller_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='aip',
            field=models.IntegerField(null=True),
        ),
    ]
