# Generated by Django 4.1.7 on 2023-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_seller_aip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='POA',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='aadh',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='aip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='ph',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
