# Generated by Django 4.1.7 on 2023-04-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_seller_poa_alter_seller_aadh_alter_seller_aip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bd',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='et',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='st',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
