# Generated by Django 4.1.7 on 2023-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_seller_bd_alter_seller_et_alter_seller_st'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='et',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
