# Generated by Django 4.1.7 on 2023-04-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_seller_et'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bd',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='et',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='st',
            field=models.DateTimeField(null=True),
        ),
    ]
