# Generated by Django 4.1.7 on 2023-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_seller_et'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bd',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='st',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
