# Generated by Django 4.1.7 on 2023-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_seller_bd_alter_seller_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='simg',
            field=models.ImageField(blank=True, null=True, upload_to='seller'),
        ),
    ]
